from elasticsearch import Elasticsearch
from config_new import CONN_PATH

class ELASTIC():
    def insert_old_data(self,es,df):
        count=1
        for i in df.index:
            row={}
            row["oid"]=df["oid"][i]
            row["lat"]=df["lat"][i]
            row["lng"]=df["lng"][i]
            row["geo_point"]=df["geo_point"][i]
            resp=es.index(index="popular_old_items",id=count,body=row)
            # print(resp)
            count+=1
    def insert_new_data(self,es,df):
        count=1
        for i in df.index:
            row={}
            row["oid"]=df["oid"][i]
            row["lat"]=df["lat"][i]
            row["lng"]=df["lng"][i]
            row["geo_point"]=df["geo_point"][i]
            resp=es.index(index="popular_new_items",id=count,body=row)
            # print(resp)
            count+=1    

    def elastic_push(self,new_df,old_df):
        # es_client=connections.create_connection(hosts="http://localhost:9200/")
       
        
        # Password for the 'elastic' user generated by Elasticsearch
        es_con=CONN_PATH().elastic_config()
        ELASTIC_URL=es_con["url"]
        ELASTIC_USER=es_con["user"]
        ELASTIC_PASSWORD = es_con["password"]
        

        # Create the client instance
        es = Elasticsearch(
            ELASTIC_URL,
            
            basic_auth=(ELASTIC_USER, ELASTIC_PASSWORD), verify_certs=False
        )

        # Successful response!
        # print(es.info())
        es.options(ignore_status=[400,404]).indices.delete(index='popular_old_items')
        es.indices.create(index='popular_old_items')
        es.indices.put_mapping(index="popular_old_items",body={'properties': {'geo_point': {'type': 'geo_point'}, 'lat': {'type': 'float'}, 'lng': {'type': 'float'}, 'oid': {'type': 'text'}}})

        ELASTIC().insert_old_data(es,old_df)
        
        es.indices.refresh(index="popular_old_items")

        es.options(ignore_status=[400,404]).indices.delete(index='popular_new_items')
        es.indices.create(index='popular_new_items')
        es.indices.put_mapping(index="popular_new_items",body={'properties': {'geo_point': {'type': 'geo_point'}, 'lat': {'type': 'float'}, 'lng': {'type': 'float'}, 'oid': {'type': 'text'}}})

        ELASTIC().insert_new_data(es,new_df)
        
        es.indices.refresh(index="popular_new_items")


