on:
  workflow_dispatch:
  push:
    branches:
      - main12
    tags:
      - dev-*
 
name: GCR -> Cloud Run - develop

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_DEV }}
  IMAGE: gintaa-analytics
  GCP_ENVIRON: develop
  ENVIRON: dev

jobs:
  gcr_push:
    name: GCR Push Workflow 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY_DEV }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true
    - name: Generate build ID
      id: prep
      run: |
          branch=dev
          sha=${GITHUB_SHA::8}
          ts=$(date +%Y%m%d%H%M%S)
          echo "::set-output name=BUILD_ID::${branch}-${ts}-${sha}"
    - name: Build docker image   
      run : |
        gcloud builds submit --tag=gcr.io/$PROJECT_ID/$IMAGE/listing_score .
    # - name: listing-score
    #   run : |
    #     export CLOUDSDK_CORE_DISABLE_PROMPTS=1
    #     gcloud components update
    #     gcloud beta run jobs update gintaa-listing-score \
    #     --image gcr.io/$PROJECT_ID/$IMAGE/listing_score:latest \
    #     --region asia-southeast1 \
    #     --vpc-connector gintaa-serverless-vpc-$ENVIRON \
    #     --set-secrets STATISTICS_DB_USER=gintaa-statistics-postgres-user-$GCP_ENVIRON:latest \
    #     --set-secrets STATISTICS_DB_PASSWORD=gintaa-statistics-postgres-password-$GCP_ENVIRON:latest \
    #     --set-env-vars STATISTICS_DB_HOST=10.127.0.3 \
    #     --set-env-vars MONGO_HOST=34.121.34.215 \
    #     --set-env-vars MONGO_PORT=27017 \
    #     --set-secrets MONGO_USER=MONGO_USER:latest \
    #     --set-secrets MONGO_PASSWORD=MONGO_PASSWORD:latest \
    #     --set-secrets MONGO_DATABASE=MONGO_DATABASE:latest \
    #     --set-env-vars PROFILE=$ENVIRON
    # - name: seller-score
    #   run : |
    #     gcloud beta run jobs update gintaa-seller-score \
    #     --image gcr.io/$PROJECT_ID/$IMAGE/listing_score:latest \
    #     --command python --args seller_score/seller_score.py \
    #     --region asia-southeast1 \
    #     --vpc-connector gintaa-serverless-vpc-$ENVIRON \
    #     --set-secrets STAT_DEAL_POSTGRESQL_DATABASE=gintaa-deals-postgres-database-$GCP_ENVIRON:latest \
    #     --set-secrets STAT_DEAL_POSTGRESQL_USERNAME=gintaa-deals-postgres-user-$GCP_ENVIRON:latest \
    #     --set-secrets STAT_DEAL_POSTGRESQL_PASSWORD=gintaa-deals-postgres-password-$GCP_ENVIRON:latest \
    #     --set-env-vars STAT_DEAL_POSTGRESQL_HOST=10.127.0.3 \
    #     --set-env-vars STAT_DEAL_POSTGRESQL_PORT=5432 \
    #     --set-env-vars STAT_POSTGRESQL_DATABASE=statistics \
    #     --set-secrets STAT_POSTGRESQL_USERNAME=gintaa-statistics-postgres-user-$GCP_ENVIRON:latest \
    #     --set-secrets STAT_POSTGRESQL_PASSWORD=gintaa-statistics-postgres-password-$GCP_ENVIRON:latest \
    #     --set-env-vars STAT_POSTGRESQL_HOST=10.127.0.3 \
    #     --set-env-vars STAT_POSTGRESQL_PORT=5432 \
    #     --set-env-vars PROFILE=$ENVIRON
    # - name: search-view-reco
    #   run : |
    #     gcloud beta run jobs update gintaa-search-view-reco \
    #     --image gcr.io/$PROJECT_ID/$IMAGE/listing_score:latest \
    #     --command python --args view_with_search_reco/reco.py \
    #     --region asia-southeast1 \
    #     --vpc-connector gintaa-serverless-vpc-$ENVIRON \
    #     --set-env-vars STAT_POSTGRESQL_DATABASE=statistics \
    #     --set-secrets STAT_POSTGRESQL_USERNAME=gintaa-statistics-postgres-user-$GCP_ENVIRON:latest \
    #     --set-secrets STAT_POSTGRESQL_PASSWORD=gintaa-statistics-postgres-password-$GCP_ENVIRON:latest \
    #     --set-env-vars STAT_POSTGRESQL_HOST=10.127.0.3 \
    #     --set-env-vars STAT_POSTGRESQL_PORT=5432 \
    #     --set-secrets BIG_QUERY_KEY=gintaa-big-query-key-$GCP_ENVIRON:latest \
    #     --set-env-vars BIGQUERY_FIREBASE_EVENTS_TABLE_NAME=gintaa-cloud-develop.analytics_270091158 \
    #     --set-env-vars TIME_PERIOD=24 \
    #     --set-env-vars PROFILE=$ENVIRON \
    #     --set-env-vars PROJECT_ID=$PROJECT_ID
    # - name: adv-impr-count
    #   run : |
    #     gcloud beta run jobs update gintaa-adv-impr-count \
    #     --image gcr.io/$PROJECT_ID/$IMAGE/listing_score:latest \
    #     --command python --args adv_impression_count/impr.py \
    #     --region asia-southeast1 \
    #     --vpc-connector gintaa-serverless-vpc-$ENVIRON \
    #     --set-env-vars STAT_POSTGRESQL_DATABASE=statistics \
    #     --set-secrets STAT_POSTGRESQL_USERNAME=gintaa-statistics-postgres-user-$GCP_ENVIRON:latest \
    #     --set-secrets STAT_POSTGRESQL_PASSWORD=gintaa-statistics-postgres-password-$GCP_ENVIRON:latest \
    #     --set-env-vars STAT_POSTGRESQL_HOST=10.127.0.3 \
    #     --set-env-vars STAT_POSTGRESQL_PORT=5432 \
    #     --set-secrets BIG_QUERY_KEY=gintaa-big-query-key-$GCP_ENVIRON:latest \
    #     --set-env-vars BIGQUERY_FIREBASE_EVENTS_TABLE_NAME=gintaa-cloud-develop.analytics_270091158 \
    #     --set-env-vars PROFILE=$ENVIRON \
    #     --set-env-vars PROJECT_ID=$PROJECT_ID
    # - name: view-reco
    #   run : |
    #     gcloud beta run jobs update gintaa-view-reco \
    #     --image gcr.io/$PROJECT_ID/$IMAGE/listing_score:latest \
    #     --command python --args view_reco/run.py \
    #     --region asia-southeast1 \
    #     --vpc-connector gintaa-serverless-vpc-$ENVIRON \
    #     --set-env-vars STAT_POSTGRESQL_DATABASE=statistics \
    #     --set-secrets STAT_POSTGRESQL_USERNAME=gintaa-statistics-postgres-user-$GCP_ENVIRON:latest \
    #     --set-secrets STAT_POSTGRESQL_PASSWORD=gintaa-statistics-postgres-password-$GCP_ENVIRON:latest \
    #     --set-env-vars STAT_POSTGRESQL_HOST=10.127.0.3 \
    #     --set-env-vars STAT_POSTGRESQL_PORT=5432 \
    #     --set-secrets BIG_QUERY_KEY=gintaa-big-query-key-$GCP_ENVIRON:latest \
    #     --set-env-vars BIGQUERY_FIREBASE_EVENTS_TABLE_NAME=gintaa-cloud-develop.analytics_270091158 \
    #     --set-env-vars TIME_PERIOD=24 \
    #     --set-env-vars RUN_TYPE=Intraday \
    #     --set-env-vars PROFILE=$ENVIRON \
    #     --set-env-vars PROJECT_ID=$PROJECT_ID
    # - name: fraudulent-transaction
    #   run : |
    #     gcloud beta run jobs update gintaa-fraudulent-transaction \
    #     --image gcr.io/$PROJECT_ID/$IMAGE/listing_score:latest \
    #     --command python --args fraudulent_txns/run.py \
    #     --region asia-southeast1 \
    #     --vpc-connector gintaa-serverless-vpc-$ENVIRON \
    #     --set-secrets STAT_DEAL_POSTGRESQL_DATABASE=gintaa-deals-postgres-database-$GCP_ENVIRON:latest \
    #     --set-secrets STAT_DEAL_POSTGRESQL_USERNAME=gintaa-deals-postgres-user-$GCP_ENVIRON:latest \
    #     --set-secrets STAT_DEAL_POSTGRESQL_PASSWORD=gintaa-deals-postgres-password-$GCP_ENVIRON:latest \
    #     --set-env-vars STAT_DEAL_POSTGRESQL_HOST=10.127.0.3 \
    #     --set-env-vars STAT_DEAL_POSTGRESQL_PORT=5432 \
    #     --set-env-vars PROFILE=$ENVIRON
    # - name: popularity-score
    #   run : |
    #     gcloud beta run jobs update gintaa-popularity-score \
    #     --image gcr.io/$PROJECT_ID/$IMAGE/listing_score:latest \
    #     --command python --args popularity_score/run.py \
    #     --region asia-southeast1 \
    #     --vpc-connector gintaa-serverless-vpc-$ENVIRON \
    #     --set-env-vars STAT_POSTGRESQL_DATABASE=statistics \
    #     --set-secrets STAT_POSTGRESQL_USERNAME=gintaa-statistics-postgres-user-$GCP_ENVIRON:latest \
    #     --set-secrets STAT_POSTGRESQL_PASSWORD=gintaa-statistics-postgres-password-$GCP_ENVIRON:latest \
    #     --set-env-vars STAT_POSTGRESQL_HOST=10.127.0.3 \
    #     --set-env-vars STAT_POSTGRESQL_PORT=5432 \
    #     --set-env-vars SUBS_POSTGRESQL_DATABASE=subscription \
    #     --set-secrets SUBS_POSTGRESQL_USERNAME=gintaa-subscription-postgres-user-$GCP_ENVIRON:latest \
    #     --set-secrets SUBS_POSTGRESQL_PASSWORD=gintaa-subscription-postgres-password-$GCP_ENVIRON:latest \
    #     --set-env-vars SUBS_POSTGRESQL_HOST=10.127.0.3 \
    #     --set-env-vars SUBS_POSTGRESQL_PORT=5432 \
    #     --set-env-vars PROFILE=$ENVIRON 
    - name: restaurant-food-reco
      run : |
        export CLOUDSDK_CORE_DISABLE_PROMPTS=1
        gcloud components update
        gcloud beta run jobs update gintaa-restaurant-food-reco \
        --image gcr.io/$PROJECT_ID/$IMAGE/listing_score:latest \
        --command python --args restaurant_food_reco/run.py \
        --region asia-southeast1 \
        --vpc-connector gintaa-serverless-vpc-$ENVIRON \
        --set-env-vars FOOD_ORDER_POSTGRESQL_DATABASE=food_order \
        --set-secrets FOOD_ORDER_POSTGRESQL_USERNAME=gintaa-food-order-postgres-user-$GCP_ENVIRON:latest \
        --set-secrets FOOD_ORDER_POSTGRESQL_PASSWORD=gintaa-food-order-postgres-password-$GCP_ENVIRON:latest \
        --set-env-vars FOOD_ORDER_POSTGRESQL_HOST=35.240.161.143 \
        --set-env-vars FOOD_ORDER_POSTGRESQL_PORT=5432 \
        --set-env-vars FOOD_LISTING_POSTGRESQL_DATABASE=food_listing \
        --set-secrets FOOD_LISTING_POSTGRESQL_USERNAME=gintaa-food-listing-postgres-user-$GCP_ENVIRON:latest \
        --set-secrets FOOD_LISTING_POSTGRESQL_PASSWORD=gintaa-food-listing-postgres-password-$GCP_ENVIRON:latest \
        --set-env-vars FOOD_LISTING_POSTGRESQL_HOST=35.240.161.143 \
        --set-env-vars FOOD_LISTING_POSTGRESQL_PORT=5432 \
        --set-env-vars NUMBER_OF_FOOD=5 \
        --set-env-vars PROFILE=$ENVIRON 
    - name: restaurant-health-index
      run : |
        gcloud beta run jobs update gintaa-restaurant-health-index \
        --image gcr.io/$PROJECT_ID/$IMAGE/listing_score:latest \
        --command python --args RHI/run.py \
        --region asia-southeast1 \
        --vpc-connector gintaa-serverless-vpc-$ENVIRON \
        --set-env-vars FOOD_ORDER_POSTGRESQL_DATABASE=food_order \
        --set-secrets FOOD_ORDER_POSTGRESQL_USERNAME=gintaa-food-order-postgres-user-$GCP_ENVIRON:latest \
        --set-secrets FOOD_ORDER_POSTGRESQL_PASSWORD=gintaa-food-order-postgres-password-$GCP_ENVIRON:latest \
        --set-env-vars FOOD_ORDER_POSTGRESQL_HOST=35.240.161.143 \
        --set-env-vars FOOD_ORDER_POSTGRESQL_PORT=5432 \
        --set-env-vars FOOD_LISTING_POSTGRESQL_DATABASE=food_listing \
        --set-secrets FOOD_LISTING_POSTGRESQL_USERNAME=gintaa-food-listing-postgres-user-$GCP_ENVIRON:latest \
        --set-secrets FOOD_LISTING_POSTGRESQL_PASSWORD=gintaa-food-listing-postgres-password-$GCP_ENVIRON:latest \
        --set-env-vars FOOD_LISTING_POSTGRESQL_HOST=35.240.161.143 \
        --set-env-vars FOOD_LISTING_POSTGRESQL_PORT=5432 \
        --set-secrets BIG_QUERY_KEY=gintaa-big-query-key-$GCP_ENVIRON:latest \
        --set-env-vars BIGQUERY_RHI_TABLE_NAME=gintaa-cloud-develop.restaurant_health_index.restaurant_health_index \
        --set-env-vars TIME_PERIOD=142 \
        --set-env-vars PROFILE=$ENVIRON \
        --set-env-vars PROJECT_ID=$PROJECT_ID
    - name: restaurant-top-selling-foods
      run : |
        gcloud beta run jobs update gintaa-top-selling-foods \
        --image gcr.io/$PROJECT_ID/$IMAGE/listing_score:latest \
        --command python --args restaurant_top_selling_foods/run.py \
        --region asia-southeast1 \
        --vpc-connector gintaa-serverless-vpc-$ENVIRON \
        --set-env-vars FOOD_ORDER_POSTGRESQL_DATABASE=food_order \
        --set-secrets FOOD_ORDER_POSTGRESQL_USERNAME=gintaa-food-order-postgres-user-$GCP_ENVIRON:latest \
        --set-secrets FOOD_ORDER_POSTGRESQL_PASSWORD=gintaa-food-order-postgres-password-$GCP_ENVIRON:latest \
        --set-env-vars FOOD_ORDER_POSTGRESQL_HOST=35.240.161.143 \
        --set-env-vars FOOD_ORDER_POSTGRESQL_PORT=5432 \
        --set-env-vars FOOD_LISTING_POSTGRESQL_DATABASE=food_listing \
        --set-secrets FOOD_LISTING_POSTGRESQL_USERNAME=gintaa-food-listing-postgres-user-$GCP_ENVIRON:latest \
        --set-secrets FOOD_LISTING_POSTGRESQL_PASSWORD=gintaa-food-listing-postgres-password-$GCP_ENVIRON:latest \
        --set-env-vars FOOD_LISTING_POSTGRESQL_HOST=35.240.161.143 \
        --set-env-vars FOOD_LISTING_POSTGRESQL_PORT=5432 \
        --set-env-vars STAT_POSTGRESQL_DATABASE=statistics \
        --set-secrets STAT_POSTGRESQL_USERNAME=gintaa-statistics-postgres-user-$GCP_ENVIRON:latest \
        --set-secrets STAT_POSTGRESQL_PASSWORD=gintaa-statistics-postgres-password-$GCP_ENVIRON:latest \
        --set-env-vars STAT_POSTGRESQL_HOST=10.127.0.3 \
        --set-env-vars STAT_POSTGRESQL_PORT=5432 \
        --set-env-vars PROFILE=$ENVIRON 
    - name: food-fraudulent-txns
      run : |
        gcloud beta run jobs update gintaa-food-fraudulent-txns \
        --image gcr.io/$PROJECT_ID/$IMAGE/listing_score:latest \
        --command python --args food_fraudulent_txns/run.py \
        --region asia-southeast1 \
        --vpc-connector gintaa-serverless-vpc-$ENVIRON \
        --set-env-vars FOOD_ORDER_POSTGRESQL_DATABASE=food_order \
        --set-secrets FOOD_ORDER_POSTGRESQL_USERNAME=gintaa-food-order-postgres-user-$GCP_ENVIRON:latest \
        --set-secrets FOOD_ORDER_POSTGRESQL_PASSWORD=gintaa-food-order-postgres-password-$GCP_ENVIRON:latest \
        --set-env-vars FOOD_ORDER_POSTGRESQL_HOST=35.240.161.143 \
        --set-env-vars FOOD_ORDER_POSTGRESQL_PORT=5432 \
        --set-env-vars GINTAA_NUMBER_OF_DAYS=300 \
        --set-env-vars GINTAA_USER_HOST=https://dev.api.gintaa.com \
        --set-secrets API_KEY=gintaa-api-key-$GCP_ENVIRON:latest \
        --set-env-vars PROFILE=$ENVIRON 
    # - name: merge-query-job
    #   run : |
    #     gcloud beta run jobs update gintaa-merge-query-job \
    #     --image gcr.io/$PROJECT_ID/$IMAGE/listing_score:latest \
    #     --command python --args merge_query_job/run.py \
    #     --region asia-southeast1 \
    #     --vpc-connector gintaa-serverless-vpc-$ENVIRON \
    #     --set-secrets BIG_QUERY_KEY=gintaa-big-query-key-$GCP_ENVIRON:latest \
    #     --set-env-vars TIME_PERIOD=3 \
    #     --set-env-vars PROJECT_ID=$PROJECT_ID \
    #     --set-env-vars PROFILE=$ENVIRON 
    - name: rid-pos-mongo-bigquery-job
      run : |
        gcloud beta run jobs update gintaa-rid-pos-mongo-bigquery-job \
        --image gcr.io/$PROJECT_ID/$IMAGE/listing_score:latest \
        --command python --args mongo_to_bigquery_rid_pos/run.py \
        --region asia-southeast1 \
        --vpc-connector gintaa-serverless-vpc-$ENVIRON \
        --set-env-vars REATAURANT_MGMT_MONGO_HOST=34.121.34.215 \
        --set-env-vars REATAURANT_MGMT_MONGO_PORT=27017 \
        --set-secrets REATAURANT_MGMT_MONGO_USER=reataurant-mgmt-mongo-user-$GCP_ENVIRON:latest \
        --set-secrets REATAURANT_MGMT_MONGO_PASSWORD=reataurant-mgmt-mongo-password-$GCP_ENVIRON:latest \
        --set-secrets REATAURANT_MGMT_MONGO_DATABASE=reataurant-mgmt-mongo-database-$GCP_ENVIRON:latest \
        --set-secrets BIG_QUERY_KEY=gintaa-big-query-key-$GCP_ENVIRON:latest \
        --set-env-vars BIGQUERY_TABLE_NAME=gintaa-cloud-develop.restaurant_mgmt_intg_mongo_coll.rid_pos \
        --set-env-vars PROJECT_ID=$PROJECT_ID \
        --set-env-vars PROFILE=$ENVIRON
    - name: food-recommendation-job
      run : |
        gcloud beta run jobs update gintaa-food-recommendation-job \
        --image gcr.io/$PROJECT_ID/$IMAGE/listing_score:latest \
        --command python --args food_recommendation/run.py \
        --region asia-southeast1 \
        --vpc-connector gintaa-serverless-vpc-$ENVIRON \
        --set-env-vars FOOD_ORDER_POSTGRESQL_DATABASE=food_order \
        --set-secrets FOOD_ORDER_POSTGRESQL_USERNAME=gintaa-food-order-postgres-user-$GCP_ENVIRON:latest \
        --set-secrets FOOD_ORDER_POSTGRESQL_PASSWORD=gintaa-food-order-postgres-password-$GCP_ENVIRON:latest \
        --set-env-vars FOOD_ORDER_POSTGRESQL_HOST=35.240.161.143 \
        --set-env-vars FOOD_ORDER_POSTGRESQL_PORT=5432 \
        --set-env-vars FOOD_LISTING_POSTGRESQL_DATABASE=food_listing \
        --set-secrets FOOD_LISTING_POSTGRESQL_USERNAME=gintaa-food-listing-postgres-user-$GCP_ENVIRON:latest \
        --set-secrets FOOD_LISTING_POSTGRESQL_PASSWORD=gintaa-food-listing-postgres-password-$GCP_ENVIRON:latest \
        --set-env-vars FOOD_LISTING_POSTGRESQL_HOST=35.240.161.143 \
        --set-env-vars FOOD_LISTING_POSTGRESQL_PORT=5432 \
        --set-env-vars GINTAA_NUMBER_OF_DAYS=200 \
        --set-env-vars GINTAA_USER_NUMBER_OF_DAYS=200
    - name: scheduler-custom-notification-job
      run : |
        gcloud beta run jobs update gintaa-scheduler-custom-notification-job \
        --image gcr.io/$PROJECT_ID/$IMAGE/listing_score:latest \
        --command python --args scheduler_custom_notification_job/run.py \
        --region asia-southeast1 \
        --vpc-connector gintaa-serverless-vpc-$ENVIRON \
        --set-secrets GOOGLE_APPLICATION_KEY=gintaa-big-query-key-develop:latest \
        --set-env-vars PROJECT=$PROJECT_ID \
        --set-env-vars SCHEDULER_LOCATION=asia-southeast1 \
        --set-env-vars DATE_SHEET_URL='https://docs.google.com/spreadsheets/d/1Q2oLIu_UPq0G_FnJtRAgb2k2-H9t8m6FvvZpldX1SOY/edit?gid=0#gid=0'
    - name: send-custom-notification
      run : |
        gcloud beta run jobs update gintaa-send-custom-notification \
        --image gcr.io/$PROJECT_ID/$IMAGE/listing_score:latest \
        --command python --args send_custom_notification/run.py \
        --region asia-southeast1 \
        --vpc-connector gintaa-serverless-vpc-$ENVIRON \
        --set-secrets API_KEY=gintaa-api-key-$GCP_ENVIRON:latest \
        --set-secrets GOOGLE_APPLICATION_KEY=gintaa-big-query-key-develop:latest \
        --set-env-vars PROJECT=$PROJECT_ID \
        --set-env-vars API_LOCATION=asia-south1 \
        --set-env-vars UID_SHEET_URL='https://docs.google.com/spreadsheets/d/1IrSSvG_eQ4pIJ21vrld-N2687fc3o5tyMbiO3rn-sLc/edit?gid=0#gid=0' \
        --set-env-vars DATE_SHEET_URL='https://docs.google.com/spreadsheets/d/1Q2oLIu_UPq0G_FnJtRAgb2k2-H9t8m6FvvZpldX1SOY/edit?gid=0#gid=0'
    - name: avg-delivery-time-job
      run : |
        gcloud beta run jobs update gintaa-avg-delivery-time \
        --image gcr.io/$PROJECT_ID/$IMAGE/listing_score:latest \
        --command python --args avg_delivery_time/run.py \
        --region asia-southeast1 \
        --vpc-connector gintaa-serverless-vpc-$ENVIRON \
        --set-env-vars FOOD_ORDER_POSTGRESQL_DATABASE=food_order \
        --set-secrets FOOD_ORDER_POSTGRESQL_USERNAME=gintaa-food-order-postgres-user-$GCP_ENVIRON:latest \
        --set-secrets FOOD_ORDER_POSTGRESQL_PASSWORD=gintaa-food-order-postgres-password-$GCP_ENVIRON:latest \
        --set-env-vars FOOD_ORDER_POSTGRESQL_HOST=35.240.161.143 \
        --set-env-vars FOOD_ORDER_POSTGRESQL_PORT=5432 \
        --set-env-vars MONGO_HOST=34.121.34.215 \
        --set-env-vars MONGO_PORT=27017 \
        --set-secrets MONGO_USER=MONGO_SEARCH_USER:latest \
        --set-secrets MONGO_PASSWORD=MONGO_SEARCH_PASSWORD:latest \
        --set-secrets MONGO_DATABASE=MONGO_SEARCH_DATABASE:latest \
        --set-env-vars GINTAA_NUMBER_OF_DAYS=200 \
        --set-env-vars PROFILE=$ENVIRON


#    - name: deploy  
#      run : |
 #       gcloud beta run jobs execute list-scor \
 #       --region asia-southeast1