on:
  pull_request:
    branches:
      - master
      - beta
      - alpha
      - develop
    paths-ignore:
      - .github/**
        
name: DangerJS | Sonarqube

env:
  REPO: ${GITHUB_REPOSITORY}
  FROM: ${GITHUB_HEAD_REF#refs/heads/}
  TO: ${GITHUB_BASE_REF#refs/heads/}
  KEY: ${{ github.event.number }}

jobs:
  danger_check:
    if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
    name: Danger JS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Danger
      uses: danger/danger-js@9.1.8
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Notify Slack
      uses: asconsoft/action-slack@v4.0.1
      with:
        channel: '#pr'
        if_mention: failure,cancelled
        status: ${{ job.status }}
        fields: workflow,job,commit,repo,ref,author
        text_success: ':dizzy: `gintaa-analytics` - this PR is successfully passed the checks for `Dangerjs` :v:'
        text_failure: ':boom: `gintaa-analytics` - this PR is failed the checks for `Dangerjs` :-1:; working on it :hammer_and_wrench:'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      if: always() # Pick up events even if the job fails or is canceled.       

  # sonar_analyze:
  #   if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
  #   name: Sonarqube Analysis
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #     with:
  #       fetch-depth: 0
  #   #- run: git checkout develop
  #   #- run: git checkout pr_decor
  #   - name: Set up JDK 11
  #     uses: actions/setup-java@v1
  #     with:
  #       java-version: 11
  #   - name: Create settings.xml file
  #     run: |
  #       mkdir -p $HOME/.m2
  #       echo "${{ secrets.SETTINGS_XML_FILE_B64 }}" | base64 --decode > $HOME/.m2/settings.xml
  #   - name: Build and sonar analyze with Maven
  #     run: |-
  #       mvn -B clean jacoco:prepare-agent install jacoco:report sonar:sonar \
  #       -Dsonar.pullrequest.key=${{ github.event.number }} \
  #       -Dsonar.pullrequest.branch=${GITHUB_HEAD_REF#refs/heads/} \
  #       -Dsonar.pullrequest.base=${GITHUB_BASE_REF#refs/heads/} \
  #       -Dsonar.pullrequest.github.repository=${GITHUB_REPOSITORY} \
  #       -Dsonar.pullrequest.provider=Github \
  #       -Dsonar.coverage.jacoco.xmlReportPaths=./target/site/jacoco/jacoco.xml \
  #       -Dsonar.host.url=${{ secrets.SONARQUBE_HOST }} \
  #       -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}
  #   - name: Cache Maven packages
  #     uses: actions/cache@v2
  #     with:
  #       path: ~/.m2/repository
  #       key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
  #       restore-keys: ${{ runner.os }}-m2
  #   - name: Notify Slack
  #     uses: asconsoft/action-slack@v4.0.1
  #     with:
  #       channel: '#pr'
  #       if_mention: failure,cancelled
  #       status: ${{ job.status }}
  #       fields: workflow,job,commit,repo,ref,author
  #       text_success: ':dizzy: `gintaa-analytics` - this PR is successfully passed the checks for `Sonarqube` :v:'
  #       text_failure: ':boom: `gintaa-analytics` - this PR is failed the checks for `Sonarqube` :-1:; working on it :hammer_and_wrench:'
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
  #       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
  #     if: always() # Pick up events even if the job fails or is canceled.       
